version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
