before:
   hooks:
     - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - "7"
dockers:
  - image_templates:
    - "itzg/web-debug-server:latest"
    - "itzg/web-debug-server:{{ .Version }}"
    goarch: amd64
    build_flag_templates:
      - --platform
      - linux/amd64
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^misc:'
