version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go build

  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: build and release
          command: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/