apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-debug-server
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: web-debug-server
              servicePort: 8080
